---
- name: Create /etc/modules-load.d/k8s.conf config file
  file:
    path: "/etc/modules-load.d/k8s.conf"
    state: "touch"

- name: Add conf for /etc/modules-load.d/k8s.conf
  blockinfile:
    path: "/etc/modules-load.d/k8s.conf"
    block: |
      overlay
      br_netfilter

- name: Load overlay, br_netfilter kernel module
  shell: |
    sudo modprobe overlay
    sudo modprobe br_netfilter

- name: Set system configurations for Kubernetes networking
  file:
    path: "/etc/sysctl.d/k8s.conf"
    state: "touch"

- name: Let iptables see bridged traffic
  blockinfile:
    path: "/etc/sysctl.d/k8s.conf"
    block: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl settings
  command: sudo sysctl --system

- name: Installing firewalld
  apt:
    name: firewalld
    state: present

- name: Starting and Enabling the firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Allow Network Ports in Firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ master_ports if ('k8sControlPlanes' in group_names) else worker_ports }}"

- name: Allow masquerade in Firewalld
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes

- name: Install containerd
  shell: |
          sudo apt-get update && sudo apt-get install -y containerd
          sudo mkdir -p /etc/containerd
          sudo containerd config default | sudo tee /etc/containerd/config.toml
          sudo systemctl restart containerd