---

- name: install prerequisite packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - apt-transport-https
    - gpg
    - gpg-agent
